export const competitions = [
  { Event: 'Accounting Objective Test', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Advanced Accounting Objective Test', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Advertising Objective Test', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Agribusiness Objective Test', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Banking & Financial Systems', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Broadcast Journalism', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Business Communication', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Business Ethics', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Business Law', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Business Management', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Business Plan', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Career Portfolio', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Coding & Programming', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Community Service Project', Category: 'Chapter Event', Grades: '9-12' },
  { Event: 'Computer Applications', Category: 'Production', Grades: '9-12' },
  { Event: 'Computer Game & Simulation Programming', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Computer Problem Solving', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Customer Service', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Cybersecurity', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Data Analysis', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Data Science & AI', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Digital Animation', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Digital Video Production', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Economics', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Entrepreneurship', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Event Planning', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Financial Planning', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Financial Statement Analysis', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Future Business Educator', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Future Business Leader', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Graphic Design', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Healthcare Administration', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Hospitality & Event Management', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Human Resource Management', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Impromptu Speaking', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Insurance & Risk Management', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'International Business', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Introduction to Business Communication', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Business Concepts', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Business', Category: 'Presentation', Grades: '9-10' },
  { Event: 'Introduction to Business Procedures', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to FBLA', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Information Technology', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Marketing Concepts', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Parliamentary Procedure', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Programming', Category: 'Presentation', Grades: '9-10' },
  { Event: 'Introduction to Public Speaking', Category: 'Presentation', Grades: '9-10' },
  { Event: 'Introduction to Retail & Merchandising', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Introduction to Social Media Strategy', Category: 'Presentation', Grades: '9-10' },
  { Event: 'Introduction to Supply Chain Management', Category: 'Objective Test', Grades: '9-10' },
  { Event: 'Job Interview', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Journalism', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Local Chapter Annual Business Report', Category: 'Chapter Event', Grades: '9-12' },
  { Event: 'Management Information Systems', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Marketing', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Mobile Application Development', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Network Design', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Networking Infrastructures', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Organizational Leadership', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Parliamentary Procedure', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Personal Finance', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Project Management', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Public Administration & Management', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Public Service Announcement', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Public Speaking', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Real Estate', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Retail Management', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Sales Presentation', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Securities & Investments', Category: 'Objective Test', Grades: '9-12' },
  { Event: 'Social Media Strategies', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Sports & Entertainment Management', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Supply Chain Management', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Technology Support & Services', Category: 'Role Play', Grades: '9-12' },
  { Event: 'Visual Design', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Website Coding & Development', Category: 'Presentation', Grades: '9-12' },
  { Event: 'Website Design', Category: 'Presentation', Grades: '9-12' },
];
